exports.validate ={
    user:[
        "firstName",
        "lastName",
        "password",
        "email",
        "role",
        "phone"
    ],
    property:[
        "price",
        'aptType',
        'location',
        'title',
        'description',
        'bathrooms',
        'likeCount',
        'image'
    ]
}
exports.response={
    user:[
        "firstName",
        "lastName",
        "email",
        "role",
        "phone"
    ]
}

exports.pathData ={
    property:[
        "price",
        'aptType',
        'location',
        'title',
        'description',
        'bathrooms',
        'image'
    ]
}